### ISSUE TITLE
Informations about BCBP IATA specifications

### ISSUE THREAD

**Issue by kapik** [georgesmith46/bcbp#1]
Hey @georgesmith46,

I didn't found another way to contact you ¯\_(ツ)_/¯
I would like to know where you have found the BCBP Specifications.
You mentioned the Spec V5 but this spec doesn't contains no information on certain items.
Eg:
- Passenger description gender: only adult (0), infant (6) and infant only (4)
- Source of check-in values
- ... 

Thanks for your help 😃

**Comment by georgesmith46** [comment]
Unfortunately I was unable to find any documentation on the specific values in the BCBP specification. This leads me to believe that the values are entirely in the discretion of the airline/airport and not governed by the standard.

The example values detailed in the readme were collated after reviewing other repos on Github. The most reliable source being [this repo](https://github.com/ncredinburgh/iata-parser/tree/master/src/main/java/com/ncredinburgh/iata/specs)
