### ISSUE TITLE
flightDate format not returning time

### ISSUE THREAD

**Issue by jeremyclayton** [georgesmith46/bcbp#2]
##### Flight date is formatted only to date and year. Time is necessary to determine when checking bags are allowed. 

Without knowing moment very well seems an adjustment could be
`estimatedDate = moment.utc(currentYear.substr(0, 1) + year + dayOfYear, "YYDDDD", true);`
to include time object. 

If you would like help I'd be more than happy to see if I can resolve the issue.

**Comment by georgesmith46** [comment]
Presumably you're referring to the decoding of the barcode string. If that's the case, I don't think any of the fields in the BCBP standard hold time information.

I'd be happy for you to submit a PR on this, just bear in mind any changes will need to conform with the IATA BCBP standard (link in readme).

**Comment by groubis** [comment]
I also confirm that BCBP barcodes do not include time.
