### ISSUE TITLE
Unable to code Fastrack Field properly

### ISSUE THREAD

**Issue by bloppernd123** [georgesmith46/bcbp#507]
Hi

Fist of all thanks for creating the wonderful library and implementation for boarding card JS.

However, I am afraid that I found a bug in the implementation and it appears whenever I set the fast track flag to "Y", the generated boarding card string isn't a valid one. Could you please investigate? Thanks in advance

I am using the following version:
https://cdn.jsdelivr.net/npm/bcbp@6.0.0/dist/index.umd.js

Here's the code generated by the script:
"M1EEEEE BBB           E234234 GOTARNSK 101  12 F011A0034 130>6002A                                         Y"

Here's the part of the JS code generating the string:

let output = encode({
          data: {
            legs: [
              {
                operatingCarrierPNR: operatingCarrierPNR,
                departureAirport: departureAirport,
                arrivalAirport: arrivalAirport,
                operatingCarrierDesignator: operatingCarrierDesignator,
                flightNumber: flightNumber,
                flightDate: new Date(`${flightDate}T00:00:00.000Z`),
                compartmentCode: compartmentCode,
                seatNumber: seatNumber,
                checkInSequenceNumber: checkInSequenceNumber,
                passengerStatus: passengerStatus,
				fastTrack: "Y"
              },
            ],
            passengerName: passengerName,
          }
        });

**Comment by georgesmith46** [comment]
Hey,

The output string you've provided is missing quite a few spaces. Please can you confirm how you are validating this string?

Be careful when rendering the string since the whitespace may be collapsed to a single space (e.g. rendering on a web page without preserving whitespace)

**Comment by bloppernd123** [comment]
Pardon my very limited experience working with node.js envrionments..but I believe the encode function generated by the script hosted here (https://cdn.jsdelivr.net/npm/bcbp@6.0.0/dist/index.umd.js) isn't correct.

Even if I don't use FastTrack flag and just fill in the mandatory fields, even then the above encode function delivers extra code (**>60000**) towards the end. Please see example below

**M1ANCDE FGH           EPNRPNR OSLARNSK 101  12 Y11A 34   106>60000**

My requirement is to use to use the script in a browser and that it's portable to use in any browser, i.e. I want to use the script with fast track and possibly other fields enabled..without being dependent on node environment. May be the script hosted on https://cdn.jsdelivr.net/npm/bcbp@6.0.0/dist/index.umd.js isn't same as the one hosted here: https://github.com/georgesmith46/bcbp ?

For validation, I am using this app: https://play.google.com/store/apps/details?id=com.bighugesystems.readmybop&hl=en&gl=US

**Comment by georgesmith46** [comment]
The `>60000` is just metadata and should still be valid. I need to update the README as that section is out of date.

What I think is happening is when you take the output from `bcbp` and validate it in the app, it loses whitespace.

This is what the string should look like:
`M1DESMARAIS/LUC       EABC123 YULFRAAC 0834 226F001A0025 130>6002A                                         Y`

However, in your example, you are missing a lot of whitespace:
`M1EEEEE BBB E234234 GOTARNSK 101 12 F011A0034 130>6002A Y`

**Comment by bloppernd123** [comment]
Thanks for your comments. I read the standard and yes, the version number field is correct as it appears. I have also rectified the error that skipped several spaces. Finally I think that the real issue is with the scanner app..which is not programmed to handle the version string:
https://play.google.com/store/apps/details?id=com.bighugesystems.readmybop&hl=en&gl=US

So overall the problem is solved. Thanks for your help

**Comment by georgesmith46** [comment]
No problem 👍
