### ISSUE TITLE
How to check if bcbp is valid or not ?

### ISSUE THREAD

**Issue by dlonghi** [georgesmith46/bcbp#539]
A quick question for the bcbp experienced fellows.

How would you check if the bcbp is valid or not ?
What kind of tests/conditions would you apply there for returning a true or false? : )

Either using the the raw string or the parsed JSON.

**Comment by dlonghi** [comment]
`'M4M1DESMARAIS/LUC     EZSQMOA YULFRAAC 0834 102Y005A0033 100YPSLQY FRAYULAC 0835 102Y005A0033 100YPSLQY YULFRAAC 0836 089Y013C0024 100YPSLQY FRAYULAC 0837 089Y014C0062 100'`

```{
  "data": {
    "passengerName": "M1DESMARAIS/LUC",
    "legs": [
      {
        "operatingCarrierPNR": "ZSQMOA",
        "departureAirport": "YUL",
        "arrivalAirport": "FRA",
        "operatingCarrierDesignator": "AC",
        "flightNumber": "0834",
        "flightDate": "2023-04-12T00:00:00.000Z",
        "compartmentCode": "Y",
        "seatNumber": "005A",
        "checkInSequenceNumber": "0033",
        "passengerStatus": "1"
      },
      {
        "operatingCarrierPNR": "YPSLQY",
        "departureAirport": "FRA",
        "arrivalAirport": "YUL",
        "operatingCarrierDesignator": "AC",
        "flightNumber": "0835",
        "flightDate": "2023-04-12T00:00:00.000Z",
        "compartmentCode": "Y",
        "seatNumber": "005A",
        "checkInSequenceNumber": "0033",
        "passengerStatus": "1"
      },
      {
        "operatingCarrierPNR": "YPSLQY",
        "departureAirport": "YUL",
        "arrivalAirport": "FRA",
        "operatingCarrierDesignator": "AC",
        "flightNumber": "0836",
        "flightDate": "2023-03-30T00:00:00.000Z",
        "compartmentCode": "Y",
        "seatNumber": "013C",
        "checkInSequenceNumber": "0024",
        "passengerStatus": "1"
      },
      {
        "operatingCarrierPNR": "YPSLQY",
        "departureAirport": "FRA",
        "arrivalAirport": "YUL",
        "operatingCarrierDesignator": "AC",
        "flightNumber": "0837",
        "flightDate": "2023-03-30T00:00:00.000Z",
        "compartmentCode": "Y",
        "seatNumber": "014C",
        "checkInSequenceNumber": "0062",
        "passengerStatus": "1"
      }
    ]
  },
  "meta": {
    "formatCode": "M",
    "numberOfLegs": 4,
    "electronicTicketIndicator": "E"
  }
}```

**Comment by georgesmith46** [comment]
If you want to validate the BCBP on your own end, I'd recommend following the [BCBP standard](https://tinkrmind.files.wordpress.com/2017/09/bcbp-implementation-guide-5th-edition-june-2016.pdf) which details the mandatory fields (page 27).

I never intended to add validation to this package. However, if you can make a good case for it I can see if I can add it in.

**Comment by dlonghi** [comment]
My case is quite simple.
If the scanned code is not a valid bcbp, don't bother checking date of flight and departure airport, and try to check if that code is in another source (allowed.txt or api).

Thanks for sharing that version of the standard, it is more complete than the latest version available on iata website. Should be easy to implements the tests.
