### ISSUE TITLE
flightDate returns 2023 in 2024 for some boarding passes

### ISSUE THREAD

**Issue by dlonghi** [georgesmith46/bcbp#668]
`M2DESMARAIS/LUC        YWR78H GRUVCPAD 2847 001Y015D0006 148>5182 M3364BAD 00000000000002A0000000000000 2   AD 0101010101          NYWR78H VCPSSAAD 2991 001Y007A0031 12C2A0000000000000 2   AD 0101010101          N`

When I decode the above bcbp on https://jia.je/decode-bcbp , `flightDate` returns `"2024-01-01T00:00:00.000Z"`

When I decode it on Linux (node script.js) as in the code below, `flightDate` returns `"2023-01-01T00:00:00.000Z"`

```
import { decode } from "bcbp";

let output;

output = decode(
  "M2DESMARAIS/LUC        YWR78H GRUVCPAD 2847 001Y015D0006 148>5182 M3364BAD 00000000000002A0000000000000 2   AD 0101010101          NYWR78H VCPSSAAD 2991 001Y007A0031 12C2A0000000000000 2   AD 0101010101          N"
);
console.log(JSON.stringify(output, null, 2));
```

Could you please take a look at it ?

**Comment by dlonghi** [comment]
Got the issue on some other boarding passes. They are real boarding passes with name and ID replaced.

**flightDate with year 2023**

`M3DESMARAIS/LUCSKY     MP818E RAOVCPAD 4119 003Y010D0024 348>5180 O4003BAD 01010101010102A0000000000000 2   AD 0101010101010          NMP818E VCPCNFAD 4484 003Y020D0053 32C2A0000000000000 2   AD 0101010101010          NMP818E CNFMCZAD 4259 003Y032A0103 32C2A0000000000000 2   AD 0101010101010          N`

Json returned by jia.je/decode-bcbp
`{ "passengerName": "DESMARAIS/LUCSK", "legs": [ { "operatingCarrierPNR": "ZCFBGR", "departureAirport": "RAO", "arrivalAirport": "VCP", "operatingCarrierDesignator": "AD", "flightNumber": "4211", "flightDate": "2023-01-03T00:00:00.000Z", "compartmentCode": "Y", "seatNumber": "008C", "checkInSequenceNumber": "0024", "passengerStatus": "1", "airlineNumericCode": "000", "serialNumber": "0000000000", "internationalDocumentationVerification": "2", "fastTrack": false }, { "operatingCarrierPNR": "ZCFBGR", "departureAirport": "VCP", "arrivalAirport": "CNF", "operatingCarrierDesignator": "AD", "flightNumber": "2658", "flightDate": "2023-01-03T00:00:00.000Z", "compartmentCode": "Y", "seatNumber": "023B", "checkInSequenceNumber": "0053", "passengerStatus": "1", "airlineNumericCode": "000", "serialNumber": "0000000000", "internationalDocumentationVerification": "2", "fastTrack": false }, { "operatingCarrierPNR": "ZCFBGR", "departureAirport": "CNF", "arrivalAirport": "BPS", "operatingCarrierDesignator": "AD", "flightNumber": "2892", "flightDate": "2023-01-03T00:00:00.000Z", "compartmentCode": "Y", "seatNumber": "019D", "checkInSequenceNumber": "0062", "passengerStatus": "1", "airlineNumericCode": "000", "serialNumber": "0000000000", "internationalDocumentationVerification": "2", "fastTrack": false } ], "passengerDescription": "2", "boardingPassIssuanceSource": "W", "issuanceDate": "2024-01-01T00:00:00.000Z", "documentType": "B", "boardingPassIssuerDesignator": "AD", "baggageTagNumber": "0000000000000" }`

**Comment by dlonghi** [comment]
For comparsion, another real boarding pass but this one returns the correct year. Name and ID replaced.

**flightDate with year 2024**
`M3DESMARAIS/LUCSKY     MP818E RAOVCPAD 4119 003Y010D0024 348>5180 O4003BAD 01010101010102A0000000000000 2   AD 0101010101010          NMP818E VCPCNFAD 4484 003Y020D0053 32C2A0000000000000 2   AD 0101010101010          NMP818E CNFMCZAD 4259 003Y032A0103 32C2A0000000000000 2   AD 0101010101010          N`

Json returned by jia.je/decode-bcbp
`{ "passengerName": "DESMARAIS/LUCSKY", "legs": [ { "operatingCarrierPNR": "MP818E", "departureAirport": "RAO", "arrivalAirport": "VCP", "operatingCarrierDesignator": "AD", "flightNumber": "4119", "flightDate": "2024-01-03T00:00:00.000Z", "compartmentCode": "Y", "seatNumber": "010D", "checkInSequenceNumber": "0024", "passengerStatus": "3", "airlineNumericCode": "000", "serialNumber": "0000000000", "internationalDocumentationVerification": "2", "frequentFlyerAirlineDesignator": "AD", "frequentFlyerNumber": "0101010101010" }, { "operatingCarrierPNR": " NMP81", "departureAirport": "8E", "arrivalAirport": "VCP", "operatingCarrierDesignator": "CNF", "flightNumber": "AD 44", "flightDate": "2024-03-24T00:00:00.000Z", "compartmentCode": "0", "seatNumber": "03Y0", "checkInSequenceNumber": "20D00", "passengerStatus": "5", "airlineNumericCode": "C" }, { "operatingCarrierPNR": "2A00000", "departureAirport": "000", "arrivalAirport": "000", "operatingCarrierDesignator": "00", "flightNumber": "2 A", "flightDate": null, "compartmentCode": "1", "seatNumber": "0101", "checkInSequenceNumber": "01010", "passengerStatus": "1" } ], "passengerDescription": "0", "boardingPassIssuanceSource": "O", "issuanceDate": "2024-01-03T00:00:00.000Z", "documentType": "B", "boardingPassIssuerDesignator": "AD", "baggageTagNumber": "0101010101010" }`

**Comment by georgesmith46** [comment]
I've made a change which will hopefully fix your issue 👍
